### ISSUE TITLE
Change name to OpenSuspect, and retire old repo (name it OpenSuspect-Legacy or something)

### ISSUE THREAD

**Issue by moxvallix** [opensuspect/opensuspect#2]
We should probably do this only once we are certain this will be considered the main repo.

**Comment by vincens2005** [comment]
oldpensuspect

**Comment by orangemn6** [comment]
I think opensuspect-legacy and leave it as a public archive.

**Comment by Pythone** [comment]
opensuspect-legacy and I will set up an organization for it. Retire it and I will make sure it has a pension.

**Comment by Pythone** [comment]
It was a good point for starting

**Comment by moxvallix** [comment]
> opensuspect-legacy and I will set up an organization for it. Retire it and I will make sure it has a pension.

it doesn't need a separate org, it can just stay under ours
if there are no other objections, here or in the element chat, i will rename the repos.
